version: '3'
services:
  node_app:
    container_name: node_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    environment:
      - VIRTUAL_HOST=$DOMAIN
      - LETSENCRYPT_HOST=$DOMAIN
      - LETSENCRYPT_EMAIL=$LETS_EMAIL
      - NODE_ENV=$NODE_ENV
      - APP_MONGO_USER=$APP_MONGO_USER
      - APP_MONGO_PASS=$APP_MONGO_PASS
      - MONGO_HOSTNAME=mongodb
      - MONGO_PORT=$MONGO_PORT
      - MONGO_DB=$MONGO_DB
      - WAIT_HOSTS=mongodb:$MONGO_PORT
    links: 
      - mongodb
    volumes:
      - .:/home/node/app
      - eexam_node_modules:/home/node/app/node_modules
      - eexam_server_logs:/home/node/app/logs
      - eexam_images:/home/node/app/assets/images       
       
  mongodb:
    container_name: mongodb
    image: mongo
    ports: 
     - $MONGO_PORT_EXTERNAL:$MONGO_PORT
    volumes:
      - 'eexam_dbdata_mongo:/data/db'
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$APP_MONGO_USER
      - MONGO_INITDB_ROOT_PASSWORD=$APP_MONGO_PASS
    restart: always 
  
  # mongodb-backup:
  #   container_name: mongodb-backup
  #   image: tiredofit/mongodb-backup
  #   links:
  #    - mongodb
  #   volumes:
  #     - ./backups:/backups
  #   environment:
  #     - DB_HOST=mongodb
  #     - DB_DUMP_FREQ=1440
  #     - DB_DUMP_BEGIN=0000
  #     - DB_CLEANUP_TIME=8640
  #     - MD5=TRUE
  #     - COMPRESSION=XZ
  #    restart: always    

networks:
  default:
    external:
      name: nginx-proxy

volumes:
  eexam_dbdata_mongo: 
  eexam_node_modules:
  eexam_server_logs:
  eexam_images:
       